# Publish the repo root as a static site
[build]
  publish = "."
  command = ""

# Optional: serve index.html for all routes (static SPA-style fallback)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
